#! /usr/bin/env bash

### Définition des variables du programme
n=/dev/null
m=~/Musique

### Code source de sing

# Vérifie qu'il n'y a pas de débordements
if [[ -n $3 ]] then {
	echo "Trop d'arguments"	
	exit 1
} fi

# Vérifie que les arguments ne sont pas vides
if [[ -z $1 ]] then {
	echo "Opérande manquant"
	exit 1
} fi

# Lance une musique
if [[ $1 == "-p" ]] then {
	if [[ -f $m/$2.wav ]] then {
		mplayer &> $n nohup $m/$2.wav & &> $n
		exit 0
	}
	elif [[ -z $2 ]] then {
		echo "Veuillez préciser le nom de la musique"
		exit 1
	}
	else {
		echo "La musique $m/$2.wav n'existe pas"
		exit 1
	} fi
} fi

# Mettre la musique en pause
if [[ $1 == "-s" ]] then {
	kill -SIGSTOP $(pgrep mplayer)
	exit 0
} fi

# Mettre la musique en play
if [[ $1 == "-c" ]] then {
	kill -SIGCONT $(pgrep mplayer)
	exit 0
} fi

# Arrêter la musique
if [[ $1 == "-k" ]] then {
	kill -SIGTERM $(pgrep mplayer)
	exit 0
} fi

# Lister les musiques
if [[ $1 == "-l" ]] then {
	ls $m | cut -d "." -f 1
} fi

# Jouer toutes les musiques
if [[ $1 == "-a" ]] then {
	for var in $(sing -l)
	do
		mplayer &> $n nohup $m/$var.wav &> $n ;
	done
	exit 0
} fi
